version: '3'
services:
  ldap:
    image: risdenk/knox_nifi_testing:knox
    command: /ldap.sh

  knox:
    image: risdenk/knox_nifi_testing:knox
    ports:
    - "8443:8443"
    command: /gateway.sh
    volumes:
    - ./topologies:/knox/conf/topologies
    depends_on:
    - ldap

  nifi:
    image: risdenk/knox_nifi_testing:nifi
    ports:
    - "9091:9091"
    environment:
    - NIFI_WEB_HTTPS_PORT=9091
    - AUTH=tls
    - KEYSTORE_PATH=/certs/keystore.jks
    - KEYSTORE_PASSWORD=nifi
    - KEYSTORE_TYPE=JKS
    - TRUSTSTORE_PATH=/certs/truststore.jks
    - TRUSTSTORE_PASSWORD=password
    - TRUSTSTORE_TYPE=JKS
    - INITIAL_ADMIN_IDENTITY='CN=Random User, O=Apache, OU=NiFi, C=US'
    depends_on:
    - knox

