version: '3'
services:
  ldap:
    image: risdenk/knox_nifi_testing:knox
    command: /ldap.sh

  knox:
    image: risdenk/knox_nifi_testing:knox
    ports:
    - "8443:8443"
    command: /gateway.sh
    volumes:
    - ./topologies:/knox/conf/topologies:ro
    - ./certs:/certs:ro
    depends_on:
    - ldap

  nifi:
    image: risdenk/knox_nifi_testing:nifi
    environment:
    - AUTH=tls
    - NIFI_WEB_HTTPS_HOST=nifi
    - NIFI_WEB_HTTPS_PORT=9091
    - KEYSTORE_PATH=/certs/nifi/keystore.jks
    - KEYSTORE_PASSWORD=keystore
    - KEYSTORE_TYPE=JKS
    - TRUSTSTORE_PATH=/certs/nifi/truststore.jks
    - TRUSTSTORE_PASSWORD=truststore
    - TRUSTSTORE_TYPE=JKS
    - INITIAL_ADMIN_IDENTITY=CN=nifi, OU=NIFI
    volumes:
    - ./certs:/certs:ro
    depends_on:
    - knox

